version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password
      - MYSQL_DB=flask_notes
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: flask_notes
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: always

volumes:
  db_data:
