apiVersion: v1
kind: PersistentVolume
metadata:
  name: resource-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.100        # ваш NFS‑сервер
    path: /exports/flask-res
  persistentVolumeReclaimPolicy: Retain
