apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-pvc
  namespace: flask-notes-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi  # имя StorageClass для NFS-CSI
