apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-pvc
  namespace: flask-notes-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: resource-pv
