apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.flask-notes-app.svc.cluster.local # это имя сервиса из nfs-server.yaml
  share: /                                              # Монтируем корень экспортов (fsid=0)
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
